// ─── System field definitions catalog ────────────────────────────────────────
// Pure data — no I/O, no side effects.

import type { FieldDefinition, Operator } from "./profile-types"
import {
  TEXT_OPERATORS,
  NUMBER_OPERATORS,
  BOOLEAN_OPERATORS,
  ENUM_OPERATORS,
} from "./profile-types"

// ─── Operator shorthand sets ──────────────────────────────────────────────────

const ENUM_PLUS_EMPTY: Operator[] = [
  ...ENUM_OPERATORS,
  "is_empty",
  "is_not_empty",
]

// ─── System field definitions ─────────────────────────────────────────────────

export const SYSTEM_FIELD_DEFINITIONS: FieldDefinition[] = [
  // ── Identity ───────────────────────────────────────────────────────────────
  {
    id: "sys_name",
    orgId: null,
    clientId: null,
    key: "name",
    label: "Nombre",
    dataType: "text",
    source: "standard",
    category: "identity",
    isSensitive: false,
    allowedOperators: [...TEXT_OPERATORS],
    normalization: [{ strategy: "trim" }, { strategy: "collapse_whitespace" }],
    enumOptions: [],
    isRequiredForEval: false,
    leadsColumn: "name",
  },
  {
    id: "sys_email",
    orgId: null,
    clientId: null,
    key: "email",
    label: "Email",
    dataType: "text",
    source: "standard",
    category: "identity",
    isSensitive: true,
    allowedOperators: ["equals", "not_equals", "is_empty", "is_not_empty"],
    normalization: [{ strategy: "trim" }, { strategy: "lowercase" }],
    enumOptions: [],
    isRequiredForEval: false,
    leadsColumn: "email",
  },
  {
    id: "sys_phone",
    orgId: null,
    clientId: null,
    key: "phone",
    label: "Teléfono",
    dataType: "text",
    source: "standard",
    category: "identity",
    isSensitive: true,
    allowedOperators: ["is_empty", "is_not_empty"],
    normalization: [{ strategy: "trim" }],
    enumOptions: [],
    isRequiredForEval: false,
    leadsColumn: "phone",
  },

  // ── Location ───────────────────────────────────────────────────────────────
  {
    id: "sys_city",
    orgId: null,
    clientId: null,
    key: "city",
    label: "Ciudad",
    dataType: "text",
    source: "standard",
    category: "location",
    isSensitive: false,
    allowedOperators: [...TEXT_OPERATORS],
    normalization: [
      { strategy: "trim" },
      { strategy: "lowercase" },
      { strategy: "remove_accents" },
      { strategy: "collapse_whitespace" },
    ],
    enumOptions: [],
    isRequiredForEval: false,
    leadsColumn: "city",
  },
  {
    id: "sys_city_canonical",
    orgId: null,
    clientId: null,
    key: "city_canonical",
    label: "Ciudad (canónica)",
    dataType: "text",
    source: "standard",
    category: "location",
    isSensitive: false,
    allowedOperators: [...TEXT_OPERATORS],
    normalization: [
      { strategy: "trim" },
      { strategy: "lowercase" },
      { strategy: "remove_accents" },
      { strategy: "city_alias_map" },
    ],
    enumOptions: [],
    isRequiredForEval: false,
    leadsColumn: "cityCanonical",
  },

  // ── Business ───────────────────────────────────────────────────────────────
  {
    id: "sys_negocio_normalized",
    orgId: null,
    clientId: null,
    key: "negocio_normalized",
    label: "Negocio (normalizado)",
    dataType: "enum",
    source: "standard",
    category: "business",
    isSensitive: false,
    allowedOperators: ENUM_PLUS_EMPTY,
    normalization: [{ strategy: "trim" }, { strategy: "lowercase" }],
    enumOptions: ["si", "no"],
    isRequiredForEval: false,
    leadsColumn: "negocioNormalized",
  },
  {
    id: "sys_negocio_raw",
    orgId: null,
    clientId: null,
    key: "negocio_raw",
    label: "Negocio (respuesta original)",
    dataType: "text",
    source: "standard",
    category: "business",
    isSensitive: false,
    allowedOperators: [...TEXT_OPERATORS],
    normalization: [{ strategy: "trim" }],
    enumOptions: [],
    isRequiredForEval: false,
    leadsColumn: "negocioRaw",
  },

  // ── Attribution / UTM ──────────────────────────────────────────────────────
  {
    id: "sys_utm_source",
    orgId: null,
    clientId: null,
    key: "utm_source",
    label: "UTM Source",
    dataType: "text",
    source: "standard",
    category: "attribution",
    isSensitive: false,
    allowedOperators: [...TEXT_OPERATORS],
    normalization: [{ strategy: "trim" }, { strategy: "lowercase" }],
    enumOptions: [],
    isRequiredForEval: false,
    leadsColumn: "utmSource",
  },
  {
    id: "sys_utm_medium",
    orgId: null,
    clientId: null,
    key: "utm_medium",
    label: "UTM Medium",
    dataType: "text",
    source: "standard",
    category: "attribution",
    isSensitive: false,
    allowedOperators: [...TEXT_OPERATORS],
    normalization: [{ strategy: "trim" }, { strategy: "lowercase" }],
    enumOptions: [],
    isRequiredForEval: false,
    leadsColumn: "utmMedium",
  },
  {
    id: "sys_utm_campaign",
    orgId: null,
    clientId: null,
    key: "utm_campaign",
    label: "UTM Campaign",
    dataType: "text",
    source: "standard",
    category: "attribution",
    isSensitive: false,
    allowedOperators: [...TEXT_OPERATORS],
    normalization: [{ strategy: "trim" }, { strategy: "lowercase" }],
    enumOptions: [],
    isRequiredForEval: false,
    leadsColumn: "utmCampaign",
  },
  {
    id: "sys_fbclid",
    orgId: null,
    clientId: null,
    key: "fbclid",
    label: "Facebook Click ID",
    dataType: "text",
    source: "standard",
    category: "attribution",
    isSensitive: false,
    allowedOperators: ["is_empty", "is_not_empty"],
    normalization: [],
    enumOptions: [],
    isRequiredForEval: false,
    leadsColumn: "fbclid",
  },

  // ── Device ─────────────────────────────────────────────────────────────────
  {
    id: "sys_platform",
    orgId: null,
    clientId: null,
    key: "platform",
    label: "Plataforma",
    dataType: "enum",
    source: "standard",
    category: "device",
    isSensitive: false,
    allowedOperators: ENUM_PLUS_EMPTY,
    normalization: [{ strategy: "trim" }, { strategy: "lowercase" }],
    enumOptions: ["facebook", "instagram", "meta", "direct", "organic"],
    isRequiredForEval: false,
    leadsColumn: "platform",
  },
  {
    id: "sys_device",
    orgId: null,
    clientId: null,
    key: "device",
    label: "Dispositivo",
    dataType: "enum",
    source: "standard",
    category: "device",
    isSensitive: false,
    allowedOperators: ENUM_PLUS_EMPTY,
    normalization: [{ strategy: "trim" }, { strategy: "lowercase" }],
    enumOptions: ["mobile", "desktop"],
    isRequiredForEval: false,
    leadsColumn: "device",
  },

  // ── E-commerce events ──────────────────────────────────────────────────────
  {
    id: "sys_ecom_cart_value",
    orgId: null,
    clientId: null,
    key: "ecom_cart_value",
    label: "Valor del carrito",
    dataType: "number",
    source: "event",
    category: "ecommerce",
    isSensitive: false,
    allowedOperators: [...NUMBER_OPERATORS],
    normalization: [{ strategy: "parse_number" }],
    enumOptions: [],
    isRequiredForEval: false,
    eventConfig: {
      eventType: "add_to_cart",
      aggregation: "sum",
      valueField: "value",
    },
  },
  {
    id: "sys_ecom_checkout_started",
    orgId: null,
    clientId: null,
    key: "ecom_checkout_started",
    label: "Inicio de checkout",
    dataType: "boolean",
    source: "event",
    category: "ecommerce",
    isSensitive: false,
    allowedOperators: [...BOOLEAN_OPERATORS],
    normalization: [{ strategy: "parse_boolean", trueValues: ["true", "1"], falseValues: ["false", "0"] }],
    enumOptions: [],
    isRequiredForEval: false,
    eventConfig: {
      eventType: "begin_checkout",
      aggregation: "any",
    },
  },
  {
    id: "sys_ecom_cart_abandoned",
    orgId: null,
    clientId: null,
    key: "ecom_cart_abandoned",
    label: "Carrito abandonado",
    dataType: "boolean",
    source: "event",
    category: "ecommerce",
    isSensitive: false,
    allowedOperators: [...BOOLEAN_OPERATORS],
    normalization: [{ strategy: "parse_boolean", trueValues: ["true", "1"], falseValues: ["false", "0"] }],
    enumOptions: [],
    isRequiredForEval: false,
    eventConfig: {
      eventType: "checkout_abandoned",
      aggregation: "any",
    },
  },
  {
    id: "sys_ecom_form_submitted",
    orgId: null,
    clientId: null,
    key: "ecom_form_submitted",
    label: "Formulario enviado",
    dataType: "boolean",
    source: "event",
    category: "ecommerce",
    isSensitive: false,
    allowedOperators: [...BOOLEAN_OPERATORS],
    normalization: [{ strategy: "parse_boolean", trueValues: ["true", "1"], falseValues: ["false", "0"] }],
    enumOptions: [],
    isRequiredForEval: false,
    eventConfig: {
      eventType: "form_submitted",
      aggregation: "any",
    },
  },
  {
    id: "sys_ecom_info_requested",
    orgId: null,
    clientId: null,
    key: "ecom_info_requested",
    label: "Info solicitada",
    dataType: "boolean",
    source: "event",
    category: "ecommerce",
    isSensitive: false,
    allowedOperators: [...BOOLEAN_OPERATORS],
    normalization: [{ strategy: "parse_boolean", trueValues: ["true", "1"], falseValues: ["false", "0"] }],
    enumOptions: [],
    isRequiredForEval: false,
    eventConfig: {
      eventType: "info_requested",
      aggregation: "any",
    },
  },
  {
    id: "sys_ecom_payment_failed",
    orgId: null,
    clientId: null,
    key: "ecom_payment_failed",
    label: "Pago fallido",
    dataType: "boolean",
    source: "event",
    category: "ecommerce",
    isSensitive: false,
    allowedOperators: [...BOOLEAN_OPERATORS],
    normalization: [{ strategy: "parse_boolean", trueValues: ["true", "1"], falseValues: ["false", "0"] }],
    enumOptions: [],
    isRequiredForEval: false,
    eventConfig: {
      eventType: "payment_failed",
      aggregation: "any",
    },
  },
  {
    id: "sys_ecom_view_count",
    orgId: null,
    clientId: null,
    key: "ecom_view_count",
    label: "Vistas de producto",
    dataType: "number",
    source: "event",
    category: "ecommerce",
    isSensitive: false,
    allowedOperators: [...NUMBER_OPERATORS],
    normalization: [{ strategy: "parse_number" }],
    enumOptions: [],
    isRequiredForEval: false,
    eventConfig: {
      eventType: "view_product",
      aggregation: "count",
    },
  },
  {
    id: "sys_ecom_product_id",
    orgId: null,
    clientId: null,
    key: "ecom_product_id",
    label: "ID de producto visto",
    dataType: "text",
    source: "event",
    category: "ecommerce",
    isSensitive: false,
    allowedOperators: [...TEXT_OPERATORS],
    normalization: [{ strategy: "trim" }],
    enumOptions: [],
    isRequiredForEval: false,
    eventConfig: {
      eventType: "view_product",
      aggregation: "latest_value",
      valueField: "product_id",
    },
  },
  {
    id: "sys_ecom_category",
    orgId: null,
    clientId: null,
    key: "ecom_category",
    label: "Categoría de producto",
    dataType: "text",
    source: "event",
    category: "ecommerce",
    isSensitive: false,
    allowedOperators: [...TEXT_OPERATORS],
    normalization: [{ strategy: "trim" }, { strategy: "lowercase" }],
    enumOptions: [],
    isRequiredForEval: false,
    eventConfig: {
      eventType: "view_product",
      aggregation: "latest_value",
      valueField: "category",
    },
  },
  {
    id: "sys_ecom_purchased",
    orgId: null,
    clientId: null,
    key: "ecom_purchased",
    label: "Compra completada",
    dataType: "boolean",
    source: "event",
    category: "ecommerce",
    isSensitive: false,
    allowedOperators: [...BOOLEAN_OPERATORS],
    normalization: [{ strategy: "parse_boolean", trueValues: ["true", "1"], falseValues: ["false", "0"] }],
    enumOptions: [],
    isRequiredForEval: false,
    eventConfig: {
      eventType: "purchase",
      aggregation: "any",
    },
  },
  {
    id: "sys_ecom_is_returning",
    orgId: null,
    clientId: null,
    key: "ecom_is_returning",
    label: "Cliente recurrente",
    dataType: "boolean",
    source: "ecommerce",
    category: "ecommerce",
    isSensitive: false,
    allowedOperators: [...BOOLEAN_OPERATORS],
    normalization: [{ strategy: "parse_boolean", trueValues: ["true", "1"], falseValues: ["false", "0"] }],
    enumOptions: [],
    isRequiredForEval: false,
  },
]

// ─── Lookups ──────────────────────────────────────────────────────────────────

const _byKey = new Map<string, FieldDefinition>(
  SYSTEM_FIELD_DEFINITIONS.map((f) => [f.key, f])
)

export function getSystemFieldByKey(key: string): FieldDefinition | undefined {
  return _byKey.get(key)
}

export function getFieldsByCategory(category: string): FieldDefinition[] {
  return SYSTEM_FIELD_DEFINITIONS.filter((f) => f.category === category)
}

// ─── Category labels (for UI) ─────────────────────────────────────────────────

export const ALL_FIELD_CATEGORIES: { value: string; label: string }[] = [
  { value: "identity",    label: "Identidad" },
  { value: "location",   label: "Ubicación" },
  { value: "business",   label: "Negocio" },
  { value: "attribution", label: "Atribución / UTM" },
  { value: "device",     label: "Dispositivo" },
  { value: "ecommerce",  label: "E-commerce" },
  { value: "behavior",   label: "Comportamiento" },
  { value: "custom",     label: "Personalizado" },
]
