import { z } from "zod"
import { CreateConversionDefinitionSchema } from "./types"

type TemplateType = "lead_gen" | "ecommerce" | "bookings"

type ConversionTemplate = Omit<z.infer<typeof CreateConversionDefinitionSchema>, "clientId" | "trackingSiteId">

const LEAD_GEN_TEMPLATES: ConversionTemplate[] = [
  {
    internalKey: "page_view",
    displayName: "Vista de Página",
    provider: "meta_pixel",
    providerEventName: "PageView",
    expectedSource: "browser",
    triggerType: "page_load",
    criticality: "low",
    freshnessPolicyDays: 30,
    enabled: true,
    triggerConfig: {},
    requiredParameters: [],
    installationNotes: "Incluido automáticamente por el código base del Pixel. Verificar que el pixel base esté instalado en todas las páginas.",
  },
  {
    internalKey: "view_content",
    displayName: "Vista de Contenido",
    provider: "meta_pixel",
    providerEventName: "ViewContent",
    expectedSource: "browser",
    triggerType: "page_load",
    criticality: "low",
    freshnessPolicyDays: 30,
    enabled: true,
    triggerConfig: {},
    requiredParameters: [],
    installationNotes: "Disparar en páginas de servicios o landing pages relevantes. Añadir content_name y content_category cuando estén disponibles.",
  },
  {
    internalKey: "lead",
    displayName: "Lead",
    provider: "both",
    providerEventName: "Lead",
    expectedSource: "both",
    triggerType: "explicit_callback",
    criticality: "critical",
    freshnessPolicyDays: 7,
    enabled: true,
    triggerConfig: {},
    requiredParameters: ["event_id"],
    installationNotes: "Disparar únicamente en el callback de éxito del formulario (no al abrirlo). El event_id debe ser único por envío y compartido entre Pixel y CAPI para deduplicación.",
  },
  {
    internalKey: "contact",
    displayName: "Contacto",
    provider: "both",
    providerEventName: "Contact",
    expectedSource: "both",
    triggerType: "explicit_callback",
    criticality: "high",
    freshnessPolicyDays: 14,
    enabled: true,
    triggerConfig: {},
    requiredParameters: [],
    installationNotes: "Disparar cuando el usuario inicia contacto directo (clic en teléfono, WhatsApp, email). Incluir event_id para habilitar deduplicación con CAPI.",
  },
  {
    internalKey: "complete_registration",
    displayName: "Registro Completado",
    provider: "both",
    providerEventName: "CompleteRegistration",
    expectedSource: "both",
    triggerType: "explicit_callback",
    criticality: "high",
    freshnessPolicyDays: 14,
    enabled: true,
    triggerConfig: {},
    requiredParameters: ["event_id"],
    installationNotes: "Disparar al completar el registro del usuario, no al inicio. Compartir event_id con el servidor para deduplicación CAPI.",
  },
  {
    internalKey: "submit_application",
    displayName: "Solicitud Enviada",
    provider: "both",
    providerEventName: "SubmitApplication",
    expectedSource: "both",
    triggerType: "explicit_callback",
    criticality: "medium",
    freshnessPolicyDays: 14,
    enabled: true,
    triggerConfig: {},
    requiredParameters: [],
    installationNotes: "Disparar al enviar solicitudes (crédito, empleo, membresía). Añadir event_id si se implementa CAPI.",
  },
]

const ECOMMERCE_TEMPLATES: ConversionTemplate[] = [
  {
    internalKey: "page_view",
    displayName: "Vista de Página",
    provider: "meta_pixel",
    providerEventName: "PageView",
    expectedSource: "browser",
    triggerType: "page_load",
    criticality: "low",
    freshnessPolicyDays: 30,
    enabled: true,
    triggerConfig: {},
    requiredParameters: [],
    installationNotes: "Incluido automáticamente por el código base del Pixel. Verificar que el pixel base esté instalado en todas las páginas.",
  },
  {
    internalKey: "view_content",
    displayName: "Vista de Producto",
    provider: "meta_pixel",
    providerEventName: "ViewContent",
    expectedSource: "browser",
    triggerType: "page_load",
    criticality: "low",
    freshnessPolicyDays: 30,
    enabled: true,
    triggerConfig: {},
    requiredParameters: [],
    installationNotes: "Disparar en páginas de producto. Incluir content_ids, content_type: 'product', value y currency.",
  },
  {
    internalKey: "add_to_cart",
    displayName: "Agregar al Carrito",
    provider: "meta_pixel",
    providerEventName: "AddToCart",
    expectedSource: "browser",
    triggerType: "explicit_callback",
    criticality: "medium",
    freshnessPolicyDays: 14,
    enabled: true,
    triggerConfig: {},
    requiredParameters: [],
    installationNotes: "Disparar en el callback del botón 'Agregar al carrito'. Incluir content_ids, value y currency.",
  },
  {
    internalKey: "initiate_checkout",
    displayName: "Iniciar Pago",
    provider: "meta_pixel",
    providerEventName: "InitiateCheckout",
    expectedSource: "browser",
    triggerType: "explicit_callback",
    criticality: "high",
    freshnessPolicyDays: 7,
    enabled: true,
    triggerConfig: {},
    requiredParameters: [],
    installationNotes: "Disparar cuando el usuario llega a la página de checkout o hace clic en 'Proceder al pago'. Incluir value, currency y num_items.",
  },
  {
    internalKey: "purchase",
    displayName: "Compra",
    provider: "both",
    providerEventName: "Purchase",
    expectedSource: "both",
    triggerType: "explicit_callback",
    criticality: "critical",
    freshnessPolicyDays: 3,
    enabled: true,
    triggerConfig: {},
    requiredParameters: ["event_id", "value", "currency", "order_id"],
    installationNotes: "Disparar en la página de confirmación de orden. CRÍTICO: event_id debe ser el order_id u otro ID único por transacción. CAPI debe enviar el mismo event_id. Nunca disparar en el frontend sin confirmación del backend.",
  },
]

const BOOKINGS_TEMPLATES: ConversionTemplate[] = [
  {
    internalKey: "page_view",
    displayName: "Vista de Página",
    provider: "meta_pixel",
    providerEventName: "PageView",
    expectedSource: "browser",
    triggerType: "page_load",
    criticality: "low",
    freshnessPolicyDays: 30,
    enabled: true,
    triggerConfig: {},
    requiredParameters: [],
    installationNotes: "Incluido automáticamente por el código base del Pixel. Verificar que el pixel base esté instalado en todas las páginas.",
  },
  {
    internalKey: "view_content",
    displayName: "Vista de Servicio",
    provider: "meta_pixel",
    providerEventName: "ViewContent",
    expectedSource: "browser",
    triggerType: "page_load",
    criticality: "low",
    freshnessPolicyDays: 30,
    enabled: true,
    triggerConfig: {},
    requiredParameters: [],
    installationNotes: "Disparar en páginas de servicios o calendarios de agendamiento. Incluir content_name con el nombre del servicio.",
  },
  {
    internalKey: "contact",
    displayName: "Contacto",
    provider: "both",
    providerEventName: "Contact",
    expectedSource: "both",
    triggerType: "explicit_callback",
    criticality: "medium",
    freshnessPolicyDays: 14,
    enabled: true,
    triggerConfig: {},
    requiredParameters: [],
    installationNotes: "Disparar cuando el usuario hace clic en teléfono, WhatsApp o email de contacto.",
  },
  {
    internalKey: "lead",
    displayName: "Lead",
    provider: "both",
    providerEventName: "Lead",
    expectedSource: "both",
    triggerType: "explicit_callback",
    criticality: "high",
    freshnessPolicyDays: 7,
    enabled: true,
    triggerConfig: {},
    requiredParameters: ["event_id"],
    installationNotes: "Disparar al completar formularios de interés o solicitud de información. El event_id debe ser único por envío.",
  },
  {
    internalKey: "appointment_booked",
    displayName: "Cita Agendada",
    provider: "both",
    providerEventName: "Lead",
    expectedSource: "both",
    triggerType: "explicit_callback",
    criticality: "critical",
    freshnessPolicyDays: 3,
    enabled: true,
    triggerConfig: {},
    requiredParameters: ["event_id"],
    // Se mapea a "Lead" en Meta porque es el estándar recomendado para citas;
    // el nombre interno permite diferenciarlo de otros leads en reporting.
    installationNotes: "Disparar SOLO cuando la cita queda confirmada en el sistema (no al abrir el calendario). El event_id debe ser el ID de la cita. CAPI debe confirmar la cita desde el servidor.",
  },
]

const TEMPLATES: Record<TemplateType, ConversionTemplate[]> = {
  lead_gen: LEAD_GEN_TEMPLATES,
  ecommerce: ECOMMERCE_TEMPLATES,
  bookings: BOOKINGS_TEMPLATES,
}

export function getTemplate(type: TemplateType): ConversionTemplate[] {
  return TEMPLATES[type]
}
